---
- name: Create client directory
  file:
    path: "{{ feedbacksite_root }}/www/dialog/"
    state: directory
    group: "{{ feedbacksite_user }}"
    owner: "{{ feedbacksite_user }}"
  tags: [sites,sites-feedback]
- name: Copy feedback for dialog
  template:
    src: dialog.php
    dest: "{{ feedbacksite_root }}/www/dialog/index.php"
    group: "{{ feedbacksite_user }}"
    owner: "{{ feedbacksite_user }}"
  tags: [sites,sites-feedback]
- name: Copy feedback site
  template:
    src: web.php
    dest: "{{ feedbacksite_root }}/www/index.php"
    group: "{{ feedbacksite_user }}"
    owner: "{{ feedbacksite_user }}"
  tags: [sites,sites-feedback]
