#!/bin/bash

set -e

if [ $# -eq 1 ]; then
	TEST=$1;
else
	TEST="all";
fi

if [ ! -d /opt/ansible/ ]; then
	echo "/opt/ansible needs to be mounted"
	exit 1
fi
if [ ! -f /opt/ansible/inventories/test ]; then
        echo "/opt/ansible/inventories/test must exist"
        exit 1
fi
ansible-playbook -i /opt/ansible/inventories/test /opt/ansible/$TEST.yml
if [ -f /opt/ansible/tests/$TEST.sh ]; then
       	/opt/ansible/tests/$TEST.sh
fi
