#!/bin/bash
if [ $# -eq 0 ]
then
        ansible-playbook -i /opt/ansible/test /opt/ansible/all.yml --vault-password-file=/opt/ansible/.vault-password
fi

if [ $# -eq 1 ]
then
        ansible-playbook -i /opt/ansible/test /opt/ansible/$1 --vault-password-file=/opt/ansible/.vault-password
	if [ -f /opt/ansible/tests/$1 ]; then
        	/opt/ansible/tests/$1
	fi
fi
