---
- name: Install git
  apt:
    name: git
    state: installed
- name: Copy Updates site
  git:
    depth: 1
    accept_hostkey: yes
    force: yes
    update: yes
    repo: git@github.com:dmdirc/updater-website.git
    dest: "{{ updatessite_root }}/www"
  tags: [sites,sites-updates]
