---
- name: Check dependencies
  apt:
    name: unzip
    state: installed

- name: Crate arfifactory group
  group:
   name: "{{ artifactory_user }}"
   state: present

- name: Create artifactory user
  user:
    name: "{{ artifactory_user }}"
    comment: "{{ artifactory_user }} user"
    group: "{{ artifactory_user }}"
    home: "/home/{{ artifactory_user }}"

- name: Download artifactory
  get_url:
    url: "http://dl.bintray.com/content/jfrog/artifactory/artifactory-{{ artifactory_version }}.zip"
    dest: "/home/{{ artifactory_user }}"

- name: Extract artifactory
  unarchive:
    src: "/home/{{ artifactory_user }}/artifactory-{{ artifactory_version }}.zip"
    creates: "/home/{{ artifactory_user }}/artifactory-{{ artifactory_version }}"
    dest: "/home/{{ artifactory_user }}"
    group: "{{ artifactory_user }}"
    owner: "{{ artifactory_user }}"
    creates: /home/{{ artifactory_user }}/artifactory-{{ artifactory_version }}

- name: Create artifactory service
  command: /home/{{ artifactory_user }}/artifactory-{{ artifactory_version }}/bin/installService.sh creates=/etc/init.d/artifactory

- name: Increase initial wait time for service
  replace:
   dest: /etc/init.d/artifactory
   regexp: while \[ \$SHUTDOWN_PORT -eq 0 \] && \[ \$nbSeconds -lt 60 \]; do
   replace: while [ $SHUTDOWN_PORT -eq 0 ] && \[ $nbSeconds -lt 90 ]; do

- name: Configure artifactory
  template:
    src: default
    dest: /etc/opt/jfrog/artifactory/default
    group: "{{ artifactory_user }}"
    owner: "{{ artifactory_user }}"

- name: Create application configuration
  template:
    src: config.xml
    dest: /home/{{ artifactory_user }}/artifactory-{{ artifactory_version}}/etc/artifactory.config.import.xml
    group: "{{ artifactory_user }}"
    owner: "{{ artifactory_user }}"

- name: Create security configuration
  template:
    src: security.xml
    dest: /home/{{ artifactory_user }}/artifactory-{{ artifactory_version}}/etc/security.import.xml
    group: "{{ artifactory_user }}"
    owner: "{{ artifactory_user }}"

- name: Start artifactory
  service:
    name: artifactory
    state: started
